### ISSUE TITLE
one of the commits made on december 14 broke sdxl lora training

### ISSUE THREAD

**Issue by Hugs288** [67372a/sd-scripts#13]
here is the error i get as soon as training starts

Traceback (most recent call last):
  File "J:\aistuff\LoRA_Easy_Training_Scripts\backend\sd_scripts\sdxl_train_network.py", line 228, in <module>
    trainer.train(args)
  File "J:\aistuff\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 1596, in train
    current_val_loss, average_val_loss, val_logs = self.calculate_val_loss(global_step, 0, train_dataloader, val_loss_recorder, val_dataloader, cyclic_val_dataloader, network, tokenizers, tokenize_strategy, text_encoders, text_encoding_strategy, unet, vae, noise_scheduler, vae_dtype, weight_dtype, accelerator, args, train_text_encoder)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\aistuff\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 635, in calculate_val_loss
    validation_steps = min(int(args.max_validation_steps), len(val_dataloader)) if args.max_validation_steps is not None else len(val_dataloader)

      ^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

reverting to commit 4e3f4c5837537abfa4519ea778d0360b3af1d172 fixed it

**Comment by 67372a** [comment]
@Hugs288 I realize what the issue is, will make a fix and push shortly. I reworked the logic to check several things in order to avoid unnecessary eval/train swaps for ScheduleFree optimizers (to improve performance and minimize rounding errors due to changing the parameter each call), but missed adding logic to handle if val loss was not enabled. (https://github.com/67372a/sd-scripts/commit/0b62c6e14a3ce681279661cecbebe39370ded9ca)

**Comment by 67372a** [comment]
@Hugs288 should be addressed, update and give it a try.

**Comment by ghost** [comment]
@67372a yes it seems fixed, thank you.
i noticed that you opened up issues on the main repo, i will report any other bugs i find there.
